### ISSUE TITLE
tr1

### ISSUE THREAD

**Issue by fredRos** [eos/eos#18] opened 2016-02-23 12:18 UTC
tr1 is deprecated hence <tr1/functional> and <tr1/memory> wont work any more. It has to be <functional> and <memory>

http://stackoverflow.com/questions/18284600/tr1-is-missing-which-header-or-library-am-i-missing-from-my-project-configur

**Comment by dvandyk** [comment] 2016-02-23 15:57
Duplicate of issue #17.

**Closed by dvandyk** 2016-02-23 15:57 UTC
Labels: bug
